spring.application.name=u5w3d5
spring.config.import=file:env.properties
# DB CONFIG
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
# JWT
jwt.secret=${JWT_SECRET}